#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Cycl0o0
"""Verify the pinned, locally patched src/decomp source snapshot."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parent.parent
TREE = ROOT / "src" / "decomp"
MANIFEST = ROOT / "tools" / "vendor-manifest.sha256"
UPSTREAM_COMMIT = "269d03016cd0e3d7a0b8925e02b97a319c1d0e8d"


def snapshot() -> dict[str, str]:
    result: dict[str, str] = {}
    for path in sorted(TREE.rglob("*")):
        if not path.is_file():
            continue
        relative = path.relative_to(ROOT).as_posix()
        result[relative] = hashlib.sha256(path.read_bytes()).hexdigest()
    return result


def read_manifest() -> dict[str, str]:
    result: dict[str, str] = {}
    for number, line in enumerate(MANIFEST.read_text(encoding="utf-8").splitlines(), 1):
        if not line or line.startswith("#"):
            continue
        try:
            digest, relative = line.split("  ", 1)
        except ValueError as error:
            raise ValueError(f"{MANIFEST}:{number}: malformed row") from error
        if len(digest) != 64 or relative in result:
            raise ValueError(f"{MANIFEST}:{number}: invalid or duplicate row")
        result[relative] = digest
    return result


def write_manifest(files: dict[str, str]) -> None:
    lines = [
        "# Generated by tools/check-vendor.py --write.",
        f"# Upstream zeldaret/oot commit: {UPSTREAM_COMMIT}",
    ]
    lines.extend(f"{digest}  {relative}" for relative, digest in files.items())
    MANIFEST.write_text("\n".join(lines) + "\n", encoding="utf-8")


def check_pins(include_manifest: bool = True) -> list[str]:
    failures: list[str] = []
    relatives = ["NOTICE.md", "tools/vendor.sh"]
    if include_manifest:
        relatives.append("tools/vendor-manifest.sha256")
    for relative in relatives:
        try:
            text = (ROOT / relative).read_text(encoding="utf-8")
        except OSError as error:
            failures.append(f"{relative}: cannot read pin: {error.strerror or error}")
            continue
        if UPSTREAM_COMMIT not in text:
            failures.append(f"{relative}: missing upstream pin {UPSTREAM_COMMIT}")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--write",
        action="store_true",
        help="replace the manifest after an intentional, reviewed vendor update",
    )
    args = parser.parse_args()

    files = snapshot()
    if args.write:
        failures = check_pins(include_manifest=False)
        if failures:
            print("vendor manifest: FAIL", file=sys.stderr)
            for failure in failures:
                print(f"  {failure}", file=sys.stderr)
            return 1
        write_manifest(files)
        print(f"vendor manifest: wrote {len(files)} files")
        return 0

    try:
        expected = read_manifest()
    except (OSError, ValueError) as error:
        print(f"vendor manifest: {error}", file=sys.stderr)
        return 1

    failures = check_pins()
    for relative in sorted(expected.keys() - files.keys()):
        failures.append(f"missing: {relative}")
    for relative in sorted(files.keys() - expected.keys()):
        failures.append(f"not in manifest: {relative}")
    for relative in sorted(expected.keys() & files.keys()):
        if files[relative] != expected[relative]:
            failures.append(f"checksum mismatch: {relative}")

    if failures:
        print("vendor manifest: FAIL", file=sys.stderr)
        for failure in failures:
            print(f"  {failure}", file=sys.stderr)
        return 1

    print(
        f"vendor manifest: OK — {len(files)} files, upstream {UPSTREAM_COMMIT}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
