#!/usr/bin/env python3
"""Generate src/gen/asset_symbols.c defining every symbol in
tools/undef-assets.txt from the decomp asset XMLs, plus a runtime bind manifest
(LibootAssetBind) so the loader can copy/byteswap real data from the extracted
ROM segments. No copyrighted bytes are embedded."""
import os, re, sys

OOT = os.environ.get("OOT", os.path.expanduser("~/oot-decomp"))
HERE = os.path.dirname(os.path.abspath(__file__))
XMLS = [  # (path, segment)
    (f"{OOT}/assets/xml/objects/object_link_boy.xml", 6),
    (f"{OOT}/assets/xml/objects/object_link_child.xml", 6),
    (f"{OOT}/assets/xml/objects/gameplay_keep.xml", 4),
    (f"{OOT}/assets/xml/objects/gameplay_dangeon_keep.xml", 5),
    (f"{OOT}/assets/xml/objects/object_bdoor.xml", 6),
]
BPT = {"rgba32": 32, "rgba16": 16, "ia16": 16, "ia8": 8, "ia4": 4,
       "i8": 8, "i4": 4, "ci8": 8, "ci4": 4}

wanted = [l.strip() for l in open(f"{HERE}/undef-assets.txt") if l.strip()]
found = {}   # name -> ("dl"|"tex"|..., segment, offset, size)

# gameplay_keep symbols absent from the XML's version-independent section.
# Offsets are the PAL/gc-eu layout (liboot's supported ROM family), derived by
# walking gameplay_keep.xml in Length order filtered to pal-1.1 <Version>
# blocks and then verified byte-exact against the ROM (DF terminators, vtx
# runs) — see the v0.4 gameplay_keep closure notes. NTSC/iQue shift +0x98
# after ~0xC878 and +0x498 after ~0xCDC0.
PAL_GAMEPLAY_KEEP = {
    "gLockOnArrowDL":            ("dl",  4, 0xCB70,  0x110),
    "gEffFlash1DL":              ("dl",  4, 0x10130, 0x78),
    # v0.6 projectiles: sparkle DL for elemental arrows; sits in the
    # version-dependent region, chains into gHoverBootsCircleDL@0x37E30,
    # DF terminator ROM-verified at +0x58 (see the projectile closure notes)
    "gEffSparklesDL":            ("dl",  4, 0x37880, 0x60),
    "gLensOfTruthMaskTex":       ("tex", 4, 0x1E370, 0x1000),  # i8 64x64
    "gEffIceFragment3DL":        ("dl",  4, 0x33EE0, 0x170),
    "gHoverBootsCircleDL":       ("dl",  4, 0x37E30, 0xD0),
    "gFootShadowDL":             ("dl",  4, 0x48180, 0x60),
    "gCircleShadowDL":           ("dl",  4, 0x49210, 0x50),
    "gHorseShadowDL":            ("dl",  4, 0x49AD0, 0x50),
    "gLockOnReticleTriangleDL":  ("dl",  4, 0x4D450, 0x18),
}
found.update(PAL_GAMEPLAY_KEEP)

for path, seg in XMLS:
    if not os.path.exists(path):
        continue
    txt = open(path).read()
    for m in re.finditer(r'<DList Name="(\w+)" Offset="0x([0-9A-Fa-f]+)"', txt):
        found.setdefault(m.group(1), ("dl", seg, int(m.group(2), 16), 0))
    for m in re.finditer(r'<Texture Name="(\w+)"[^>]*Format="(\w+)" Width="(\d+)" Height="(\d+)"[^>]*Offset="0x([0-9A-Fa-f]+)"', txt):
        size = int(m.group(3)) * int(m.group(4)) * BPT[m.group(2)] // 8
        found.setdefault(m.group(1), ("tex", seg, int(m.group(5), 16), size))
    for m in re.finditer(r'<Skeleton Name="(\w+)"[^>]*Offset="0x([0-9A-Fa-f]+)"', txt):
        found.setdefault(m.group(1), ("skel", seg, int(m.group(2), 16), 0))
    # pause poses etc: raw arrays of Vec3s frame data
    for m in re.finditer(r'<Array Name="(\w+)" Count="(\d+)"[^>]*Offset="0x([0-9A-Fa-f]+)"', txt):
        found.setdefault(m.group(1), ("vec3s", seg, int(m.group(3), 16), int(m.group(2)) * 6))

out = [
    "/* Generated by tools/gen_asset_symbols.py -- do not edit. */",
    '#include "ultra64.h"',
    '#include "animation.h"',
    '#include "liboot_assets.h"',
    "",
]
binds = []
missing = []

for name in wanted:
    if name == "gLinkObjectIds":
        out.append("s16 gLinkObjectIds[2] = { 0x0014 /* OBJECT_LINK_BOY */, 0x0015 /* OBJECT_LINK_CHILD */ };")
        continue
    kind, seg, off, size = found.get(name, (None, 0, 0, 0))
    tok = f"0x{(seg << 24) | off:08X}"
    if kind == "dl":
        out.append(f"Gfx {name}[] = {{ gsSPBranchList({tok}) }};")
    elif kind == "tex":
        out.append(f"u64 {name}[{max(size, 8) // 8}];")
        binds.append((name, seg, off, size, "LIBOOT_BIND_RAW"))
    elif kind == "skel":
        out.append(f"FlexSkeletonHeader {name}; /* filled by loader */")
    elif kind == "vec3s":
        out.append(f"Vec3s {name}[{size // 6}];")
        binds.append((name, seg, off, size, "LIBOOT_BIND_S16"))
    else:
        missing.append(name)
        if name.endswith("DL"):
            out.append(f"Gfx {name}[] = {{ gsSPEndDisplayList() }}; /* MISSING FROM XML */")
        elif name.endswith("Tex"):
            out.append(f"u64 {name}[512]; /* MISSING FROM XML */")
        elif name.endswith("JointTable"):
            out.append(f"Vec3s {name}[24]; /* MISSING FROM XML */")
        elif name.endswith("Skel"):
            out.append(f"FlexSkeletonHeader {name}; /* MISSING FROM XML */")
        else:
            out.append(f"u64 {name}[16]; /* MISSING FROM XML, unknown type */")

out.append("")
out.append("const LibootAssetBind gLibootAssetBinds[] = {")
for name, seg, off, size, mode in binds:
    out.append(f'    {{ "{name}", {name}, {seg}, 0x{off:X}, 0x{size:X}, {mode} }},')
out.append("};")
out.append(f"const u32 gLibootAssetBindCount = {len(binds)};")

dst = f"{HERE}/../src/gen/asset_symbols.c"
open(dst, "w").write("\n".join(out) + "\n")
print(f"generated {len(wanted)} symbols ({len(binds)} runtime binds) -> {dst}")
if missing:
    print("MISSING FROM XML (placeholders):")
    for n in missing:
        print(f"  {n}")
