#!/usr/bin/env python3
"""Generate native LinkAnimationHeader definitions from the decomp's
link_animetion.xml. Each gPlayerAnim_* symbol keeps a segment-7 token in its
.segment field (resolved by liboot's segment table at runtime), so no
copyrighted animation bytes ever land in the repo."""
import re, sys, os

OOT = os.environ.get("OOT", os.path.expanduser("~/oot-decomp"))
XML = f"{OOT}/assets/xml/misc/link_animetion.xml"
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "gen", "player_anim_headers.c")

entries = []
for m in re.finditer(r'<PlayerAnimationData Name="(\w+)_Data" FrameCount="(\d+)" Offset="0x([0-9A-Fa-f]+)"', open(XML).read()):
    entries.append((m.group(1), int(m.group(2)), int(m.group(3), 16)))

# IDs exported by liboot are the one-based order of the animation data in the
# segment-7 blob.  Sort explicitly so they stay stable if the XML is ever
# reordered without changing the ROM layout.
entries.sort(key=lambda entry: entry[2])
if len(entries) > 0x7FFF:
    raise RuntimeError("animation table no longer fits OoTLinkState.animId")
if len({name for name, _, _ in entries}) != len(entries):
    raise RuntimeError("duplicate Player animation name")
if len({off for _, _, off in entries}) != len(entries):
    raise RuntimeError("duplicate Player animation offset")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    f.write('/* Generated by tools/gen_anim_headers.py — do not edit. */\n')
    f.write('#include "ultra64.h"\n#include "animation.h"\n\n')
    for name, frames, off in entries:
        f.write(f'LinkAnimationHeader {name} = {{ {{ {frames} }}, (void *)0x{0x07000000 + off:08X} }};\n')
    f.write('\n/* Stable, one-based OoTLinkState.animId mapping (zero = unknown). */\n')
    f.write('static const void *const sLibootPlayerAnimations[] = {\n')
    for name, _, _ in entries:
        f.write(f'    &{name},\n')
    f.write('};\n\n')
    f.write('s16 liboot_player_anim_id(const void *animation)\n')
    f.write('{\n')
    f.write('    for (u32 i = 0; i < sizeof(sLibootPlayerAnimations) /\n')
    f.write('                         sizeof(sLibootPlayerAnimations[0]); ++i) {\n')
    f.write('        if (animation == sLibootPlayerAnimations[i]) return (s16)(i + 1);\n')
    f.write('    }\n')
    f.write('    return 0;\n')
    f.write('}\n')
print(f"generated {len(entries)} headers -> {OUT}")
