#!/bin/sh
# Refresh the decomp translation units listed in vendor-list.txt (one
# repo-relative path per line, '#' comments allowed) from $OOT (default
# ~/oot-decomp), preserving relative paths. The required header/asset-
# declaration closure is version-pinned in src/decomp and is not regenerated by
# this helper. Re-running this script overwrites local source patches; inspect
# the resulting diff and reapply the integration changes listed in NOTICE.md.
set -eu
OOT="${OOT:-$HOME/oot-decomp}"
cd "$(dirname "$0")/.."
while IFS= read -r f; do
    case "$f" in ''|'#'*) continue;; esac
    mkdir -p "src/decomp/$(dirname "$f")"
    cp "$OOT/$f" "src/decomp/$f"
    echo "vendored $f"
done < tools/vendor-list.txt
